### ISSUE TITLE
Plugin fails after update to node v.20

### ISSUE THREAD

**Issue by VladimirPlatonenko** [vitejs/vite-plugin-react#216]
### Describe the bug

Vite build with plugin-react usage fails after upgrade to node 20 if plugin-react is used in the vite.config.ts with following error:
failed to load config from vite.config.ts
error during build:
TypeError: Cannot redefine property: File
    at Function.defineProperty (<anonymous>)
    at Object.<anonymous> (node_modules\@babel\core\lib\index.js:7:8)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (node_modules\@babel\core\lib\config\helpers\config-api.js:16:14)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)

This can be preproduced on simple scaffolded vite-react app. As soon as you comment plugin usage in config files it all works but you obviously lose features.
As off today default node images were updated to be v20 so this caused all our container building to fail. 
Ofc we can mitigate it by either pinning node version by using version specific container or by having production-only config file(which does not need plugin enabled anyway) and running node 18 locally on dev environment for now. But this all are workarounds.

### Reproduction

I cant provide stackblitz as they are pinned to node 16

### Steps to reproduce

- update node to latest v20(20.6.0);
- scaffold simple vite-react app;
- run npm build or npm run dev.

### System Info

```shell
Happens on both windows and docker node:alpine container
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VladimirPlatonenko** [comment]
It looks like this is not a plugin issue and originates to https://github.com/nodejs/node/issues/49497.
