### ISSUE TITLE
Error Boundary issue.

### ISSUE THREAD

**Issue by mharj** [vitejs/vite-plugin-react#234]
### Describe the bug

I have CRA (pwa) base project which I'm testing to transfer over vite React.
But some reason React Lazy and Error Boundary works different way than CRA one(?)
Same structure on CRA works ok and all errors (even from lazy loaded ones) are catch to ErrorBoundary.

Sorry didn't have time to rebuild minimal test for this, but I think this should be directly testable with having Lazy component which throws error on component lifecycle calls. (or clone repo for test this)

views are just loaded like (including "broken" View which throws error)
```typescript
const HomeView = React.lazy(() => import('./views/HomeView' /* webpackChunkName: "home-view" */));
```
and base render structure
```typescript
return (
  <Router>
    <ErrorBoundary onError={ErrorView}>
      <Suspense fallback={<Loading />}>
        <Routes>
          <Route path="/" element={<HomeView />} />
....
....
....
        </Routes>
      </Suspense>
    </ErrorBoundary>
  </Router>
);
```

and error is 
```
The above error occurred in one of your React components:

    at Lazy
    at ErrorBoundary (http://localhost:5173/src/components/ErrorBoundary.tsx:44:9)
    at Router (http://localhost:5173/node_modules/.vite/deps/chunk-BDGTYZOO.js?v=699a086d:3715:15)
    at HashRouter (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=699a086d:334:5)
    at App (http://localhost:5173/src/App.tsx:41:45)
    at r2 (http://localhost:5173/node_modules/.vite/deps/react-helmet-async.js?v=699a086d:1191:21)
    at PersistGate2 (http://localhost:5173/node_modules/.vite/deps/redux-persist_integration_react.js?v=699a086d:90:5)
    at Provider (http://localhost:5173/node_modules/.vite/deps/react-redux.js?v=699a086d:1539:3)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
```

### Reproduction

https://github.com/mharj/react-typescript-vite-base

### Steps to reproduce

npm i
npm run dev 
hit "broken" button

original CRA which I'm moving to vite React
https://github.com/mharj/react-typescript-base  (npm i && npm start)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i5-10400T CPU @ 2.00GHz
    Memory: 28.92 GB / 47.74 GB
  Binaries:
    Node: 18.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.7.1 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Spartan (44.22621.2283.0), Chromium (117.0.2045.60), ChromiumDev (119.0.2132.0)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vitejs/plugin-react-swc: ^3.3.2 => 3.4.0
    vite: ^4.4.5 => 4.4.11
```

### Used Package Manager

npm

### Logs

react-dom.development.js:22839  Uncaught Error: Broken: something got broken
    at BrokenView.tsx:5:9
    at commitHookEffectListMount (react-dom.development.js:23150:26)
    at commitPassiveMountOnFiber (react-dom.development.js:24926:13)
    at commitPassiveMountEffects_complete (react-dom.development.js:24891:9)
    at commitPassiveMountEffects_begin (react-dom.development.js:24878:7)
    at commitPassiveMountEffects (react-dom.development.js:24866:3)
    at flushPassiveEffectsImpl (react-dom.development.js:27039:3)
    at flushPassiveEffects (react-dom.development.js:26984:14)
    at react-dom.development.js:26769:9
    at workLoop (scheduler.development.js:266:34)
(anonymous) @ BrokenView.tsx:5
commitHookEffectListMount @ react-dom.development.js:23150
commitPassiveMountOnFiber @ react-dom.development.js:24926
commitPassiveMountEffects_complete @ react-dom.development.js:24891
commitPassiveMountEffects_begin @ react-dom.development.js:24878
commitPassiveMountEffects @ react-dom.development.js:24866
flushPassiveEffectsImpl @ react-dom.development.js:27039
flushPassiveEffects @ react-dom.development.js:26984
(anonymous) @ react-dom.development.js:26769
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 11 more frames
Show less
react-dom.development.js:22839  Uncaught Error: Broken: something got broken
    at BrokenView.tsx:5:9
    at commitHookEffectListMount (react-dom.development.js:23150:26)
    at invokePassiveEffectMountInDEV (react-dom.development.js:25154:13)
    at invokeEffectsInDev (react-dom.development.js:27351:11)
    at commitDoubleInvokeEffectsInDEV (react-dom.development.js:27330:7)
    at flushPassiveEffectsImpl (react-dom.development.js:27056:5)
    at flushPassiveEffects (react-dom.development.js:26984:14)
    at react-dom.development.js:26769:9
    at workLoop (scheduler.development.js:266:34)
    at flushWork (scheduler.development.js:239:14)
(anonymous) @ BrokenView.tsx:5
commitHookEffectListMount @ react-dom.development.js:23150
invokePassiveEffectMountInDEV @ react-dom.development.js:25154
invokeEffectsInDev @ react-dom.development.js:27351
commitDoubleInvokeEffectsInDEV @ react-dom.development.js:27330
flushPassiveEffectsImpl @ react-dom.development.js:27056
flushPassiveEffects @ react-dom.development.js:26984
(anonymous) @ react-dom.development.js:26769
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 10 more frames
Show less
2console.js:213  The above error occurred in the <BrokenView> component:

    at BrokenView (http://localhost:5174/src/views/BrokenView.tsx:14:5)
    at RenderedRoute (http://localhost:5174/node_modules/.vite/deps/chunk-BDGTYZOO.js?v=699a086d:3327:5)
    at Routes (http://localhost:5174/node_modules/.vite/deps/chunk-BDGTYZOO.js?v=699a086d:3768:5)
    at Suspense
    at div
    at div
    at ErrorBoundary (http://localhost:5174/src/components/ErrorBoundary.tsx:44:9)
    at Router (http://localhost:5174/node_modules/.vite/deps/chunk-BDGTYZOO.js?v=699a086d:3715:15)
    at HashRouter (http://localhost:5174/node_modules/.vite/deps/react-router-dom.js?v=699a086d:334:5)
    at App (http://localhost:5174/src/App.tsx:41:45)
    at r2 (http://localhost:5174/node_modules/.vite/deps/react-helmet-async.js?v=699a086d:1191:21)
    at PersistGate2 (http://localhost:5174/node_modules/.vite/deps/redux-persist_integration_react.js?v=699a086d:90:5)
    at Provider (http://localhost:5174/node_modules/.vite/deps/react-redux.js?v=699a086d:1539:3)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
overrideMethod @ console.js:213
logCapturedError @ react-dom.development.js:18687
callback @ react-dom.development.js:18755
callCallback @ react-dom.development.js:13923
commitUpdateQueue @ react-dom.development.js:13944
commitLayoutEffectOnFiber @ react-dom.development.js:23364
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
performSyncWorkOnRoot @ react-dom.development.js:26117
flushSyncCallbacks @ react-dom.development.js:12042
flushPassiveEffectsImpl @ react-dom.development.js:27060
flushPassiveEffects @ react-dom.development.js:26984
(anonymous) @ react-dom.development.js:26769
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 19 more frames
Show less
console.js:213  The above error occurred in one of your React components:

    at Lazy
    at ErrorBoundary (http://localhost:5174/src/components/ErrorBoundary.tsx:44:9)
    at Router (http://localhost:5174/node_modules/.vite/deps/chunk-BDGTYZOO.js?v=699a086d:3715:15)
    at HashRouter (http://localhost:5174/node_modules/.vite/deps/react-router-dom.js?v=699a086d:334:5)
    at App (http://localhost:5174/src/App.tsx:41:45)
    at r2 (http://localhost:5174/node_modules/.vite/deps/react-helmet-async.js?v=699a086d:1191:21)
    at PersistGate2 (http://localhost:5174/node_modules/.vite/deps/redux-persist_integration_react.js?v=699a086d:90:5)
    at Provider (http://localhost:5174/node_modules/.vite/deps/react-redux.js?v=699a086d:1539:3)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
overrideMethod @ console.js:213
logCapturedError @ react-dom.development.js:18687
update.callback @ react-dom.development.js:18720
callCallback @ react-dom.development.js:13923
commitUpdateQueue @ react-dom.development.js:13944
commitLayoutEffectOnFiber @ react-dom.development.js:23391
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
performSyncWorkOnRoot @ react-dom.development.js:26117
flushSyncCallbacks @ react-dom.development.js:12042
flushPassiveEffectsImpl @ react-dom.development.js:27060
flushPassiveEffects @ react-dom.development.js:26984
(anonymous) @ react-dom.development.js:26769
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 19 more frames
Show less
react-dom.development.js:19055  Uncaught Error: A component suspended while responding to synchronous input. This will cause the UI to be replaced with a loading indicator. To fix, updates that suspend should be wrapped with startTransition.
    at throwException (react-dom.development.js:19055:35)
    at handleError (react-dom.development.js:26311:7)
    at renderRootSync (react-dom.development.js:26437:7)
    at recoverFromConcurrentError (react-dom.development.js:25850:20)
    at performSyncWorkOnRoot (react-dom.development.js:26096:20)
    at flushSyncCallbacks (react-dom.development.js:12042:22)
    at flushPassiveEffectsImpl (react-dom.development.js:27060:3)
    at flushPassiveEffects (react-dom.development.js:26984:14)
    at react-dom.development.js:26769:9
    at workLoop (scheduler.development.js:266:34)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
I looked at it and the error is actually because the ErrorView is also lazy and there is no suspense above the ErrorBoundary.
Adding the/another suspense above the error boundary make the project works.
I don't know why this is not the same issue with CRA, but everything seems to work as intended on the repro

**Comment by mharj** [comment]
@ArnaudBarre oh didn't notice that!, thanks I'll continue finalize this one to build new base project 😊

**Comment by mharj** [comment]
nice works like charm, thanks!
